# Generated by Django 5.0 on 2026-03-14 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_kz',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Name (kz)'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Name (ru)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Name (en)'),
        ),
    ]
