# Generated by Django 6.0.2 on 2026-03-14 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('en', 'en'), ('ru', 'ru'), ('kz', 'kz')], default='en', help_text='Preferred language for the user interface', max_length=5, verbose_name='Language'),
        ),
        migrations.AddField(
            model_name='user',
            name='timezone',
            field=models.CharField(default='UTC', help_text='Preferred timezone for the user', max_length=64, verbose_name='Timezone'),
        ),
    ]
